paiji2_carpooling/urls.py
from django.conf.urls import url  # , patterns
from django.contrib.auth.decorators import login_required

from paiji2_carpooling.views import (
   CarpoolListView,
   CarpoolCreateView,
   CarpoolEditView,
   CarpoolDeleteView,
)


urlpatterns = [
    url(
        r'^$',
        login_required(CarpoolListView.as_view()),
        name="carpool-list",
    ),
    url(
        r'add$',
        login_required(CarpoolCreateView.as_view()),
        name="carpool-create",
    ),
    url(
        r'edit/(?P<pk>[0-9]+)/$',
        login_required(CarpoolEditView.as_view()),
        name="carpool-edit",
    ),
    url(
        r'delete/(?P<pk>[0-9]+)/$',
        login_required(CarpoolDeleteView.as_view()),
        name="carpool-delete",
    ),
]

paiji2_carpooling/models.py
from datetime import timedelta, date, time
from django.utils import timezone
from django.db import models
from django.utils.translation import (
    ugettext as _,
    pgettext,
)


try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except:
    from django.conf import settings
    User = settings.AUTH_USER_MODEL


def default_good_until():
    return timezone.now() + timedelta(days=3)


def default_good_until_0():
    return date.today() + timedelta(days=3)


def default_good_until_1():
    return time(hour=18, minute=30)


class Carpool(models.Model):
    OFFER = 0
    SEARCH = 1
    ANNONCE_TYPE = (
        (OFFER, pgettext('1st p sg', 'Offer')),
        (SEARCH, pgettext('1st p sg', 'Search')),
    )

    author = models.ForeignKey(
        User,
        verbose_name=_('author'),
        related_name='covs',
    )

    annonce_type = models.IntegerField(
        _('advert type'),
        choices=ANNONCE_TYPE,
        blank=False,
    )

    good_until = models.DateTimeField(
        _('advert validity deadline'),
        default=default_good_until,
    )

    posted_at = models.DateTimeField(
        _('publication date'),
    )

    notes = models.CharField(
        _('description'),
        max_length=150,
    )

    def __unicode__(self):
        if self.annonce_type is self.OFFER:
            action = _('offers')
        else:
            action = _('searches')

        return "{author} {action} {notes}".format(
            author=self.author.get_full_name(),
            action=action,
            notes=self.notes,
        )

    def isGood(self):
        return self.good_until > timezone.now()
    isGood.short_description = _('still current ?')

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.posted_at = timezone.now()
        super(Carpool, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('carpool')
        verbose_name_plural = _('carpools')
        ordering = ('-posted_at', )

paiji2_carpooling/forms.py
from django.forms import ModelForm
from .models import Carpool
from django.contrib.admin import widgets


class CarpoolForm(ModelForm):
    class Meta:
        model = Carpool
        fields = [
            'annonce_type',
            'good_until',
            'notes',
        ]
        widgets = {
            'good_until': widgets.AdminSplitDateTime()
        }

paiji2_carpooling/views.py
from django.views import generic
from django.core.urlresolvers import reverse
from django.http import HttpResponseNotFound
from django.utils.translation import ugettext as _
from .forms import CarpoolForm
from paiji2_carpooling.models import (
    Carpool,
)
from paiji2_utils.views import SuccessUrlMixin


class MySuccessUrl(SuccessUrlMixin):

    default_url_name = 'carpool-list'

    def get_forbidden_urls(self):
        if hasattr(self, 'object'):
            return (
                reverse('carpool-edit', args=[self.object.pk]),
                reverse('carpool-delete', args=[self.object.pk]),
            )
        else:
            return None


class CarpoolOwnerMixin(object):

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update Carpools """
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseNotFound(
                _('Rezo is not hacked. You don\'t have the permission xD')
            )
        return super(CarpoolOwnerMixin, self).dispatch(
            request, *args, **kwargs
        )


class CarpoolListView(generic.ListView):

    model = Carpool
    paginate_by = 10
    context_object_name = 'covs'
    template_name = 'carpooling/carpool/list.html'

    def get_queryset(self):
        return super(CarpoolListView, self).get_queryset().select_related(
            'author'
        )


class CarpoolCreateView(MySuccessUrl, generic.CreateView):

    model = Carpool
    form_class = CarpoolForm
    template_name = 'carpooling/carpool/form.html'
    message_succes = _('Your request has been saved successfully :P')
    forbidden_url_names = (
        'carpool-create',
    )

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CarpoolCreateView, self).form_valid(form)


class CarpoolEditView(CarpoolOwnerMixin,
                      MySuccessUrl,
                      generic.UpdateView):

    model = Carpool
    form_class = CarpoolForm
    template_name = 'carpooling/carpool/form.html'
    message_success = _(
        'Your carpool has been updated, it will be refreshed in a moment'
    )


class CarpoolDeleteView(CarpoolOwnerMixin, MySuccessUrl, generic.DeleteView):
    model = Carpool
    template_name = 'carpooling/carpool/confirm_delete.html'
    message_success = _(
        'Your carpool has been removed, it will be refreshed in a moment'
    )

paiji2_carpooling/templates/carpooling/carpool/block.html
{% load readmore %}
{% load i18n %}
{% load profile %}


<h3>{% trans 'Carpool' %}</h3>
<div class="row text-center">
    {% if request.user.is_authenticated %}
    <div class="col-sm-6">
        <a class="btn btn-sm btn-default" href="{% url 'carpool-create' %}">
            {% trans 'Add a carpool' %}
        </a>
    </div>
    {% endif %}
    <div class="col-sm-6">
        <a class="btn btn-sm btn-default" href="{% url 'carpool-list' %}">
            {# Translators: Archives #}
            {% trans 'Records' %}
        </a>
    </div>
</div>

<ul class="list-unstyled">
    {% for item in cov %}

        <li>

            {% profile_link item.author %}

            <div class="pull-right">
                {% if item.author == request.user %}
                    <a href="{% url 'carpool-edit' item.id %}"><i class="fa fa-pencil"></i></a>
                    <a href="{% url 'carpool-delete' item.id %}"><i class="fa fa-trash-o"></i></a>
                {% else %}
                    {% with subject='['|add:_('carpooling')|add:'] '|add:_('About')|add:' : "'|add:item.notes|add:'"' %}
                    {% mail_link item.author '' subject %}
                    {% endwith %}
                {% endif %}
            </div>

            <br/>

            {% if item.annonce_type == 0 %}
            <span class="label label-success">
                {% trans 'Offer' context "1st p sg" %}
            </span>
            {% else %}
            <span class="label label-danger">
                {% trans 'Search' context "1st p sg" %}
            </span>
            {% endif %}

            <span class="label label-primary">
                {{ item.good_until|date:'SHORT_DATETIME_FORMAT' }}
            </span>

            <br/>

            {{ item.notes|readmore:10 }}

            <span class="text-muted">
                <small>{% blocktrans with TimeSince=item.posted_at|timesince %}{{ TimeSince }} ago{% endblocktrans %}</small>
            </span>

        </li>

        <li>
            <hr/>
        </li>

    {% endfor %}
</ul>

paiji2_carpooling/templates/carpooling/carpool/confirm_delete.html
{% extends "home/layout_three_columns.html" %}


{% load bootstrap3 %}
{% load i18n %}


{% block title %}{% trans 'Carpool deletion confirmation' %}{% endblock %}


{% block content %}
<div class="well">
    <h3>{% trans 'Do you really want to delete this carpool ?' %}</h3>
    <p>'{{ object.notes }}'</p>

    <form action="{{ request.get_full_path }}" method="post" role="form">
        {% csrf_token %}

        <input type="hidden" value="{{ request.META.HTTP_REFERER }}" name="next" />

        {% buttons %}
        <button type="submit" class="btn btn-danger btn-block">
            {% trans 'Delete' %}
        </button>
        {% endbuttons %}
        <div class="clearfix"></div>
    </form>
</div>
{% endblock %}

paiji2_carpooling/templates/carpooling/carpool/form.html
{% extends "home/layout_three_columns.html" %}


{% load bootstrap3 %}
{% load i18n %}

{% block style %}
<script type="text/javascript" src="/fr/admin/jsi18n/"></script>

<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/related-widget-wrapper.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
<link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>
<script type="text/javascript">
  window.__admin_media_prefix__ = "/static/admin/";
</script>
{% endblock %}


{% block title %}
    {% if form.instance and form.instance.pk %}
        {% trans 'Edit a carpool' %}
    {% else %}
        {% trans 'Offer/search a carpool' %}
    {% endif %}
{% endblock %}


{% block content %}
    <div class="well">
        {% if form.instance and form.instance.pk %}
            <h3>{% trans 'Edit a carpool' %}</h3>
        {% else %}
            <h3>{% trans 'Offer/search a carpool' %}</h3>
        {% endif %}

        <form action="{{ request.get_full_path }}" method="post" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label>{% trans 'Announcer' %}</label>
                <p>{{ request.user.first_name }} ({{ request.user.email }})</p>
            </div>

            <div class="form-group">
                <label for="id_annonce_type">{% trans 'Advert type' %}</label>
                {% bootstrap_field form.annonce_type show_label=False %}

                <label>{% trans 'Departure time' %}</label>
                {% comment %}
                {% bootstrap_field form.good_until show_label=False %}
                {% endcomment %}
                {{ form.good_until }}

                <label for="id_notes">{% trans 'Notes' %}</label>
                <p class="help-block">{% trans 'Ex: Metz-Paris-Compiègne, on Friday around 5pm, 3 places 15 €, back on Sunday at 6pm' %}</p>
                {% bootstrap_field form.notes show_label=False %}
            </div>

            <input type="hidden" value="{{ request.META.HTTP_REFERER }}" name="next" />
            <br />
            {% buttons %}
                <button type="submit" class="btn btn-primary btn-block text-center">
                    {% if form.instance and form.instance.pk %}
                        {% trans 'Update' %}
                    {% else %}
                        {% trans 'Publish' %}
                    {% endif %}
                </button>
            {% endbuttons %}
            <div class="clearfix"></div>
        </form>
    </div>
{% endblock %}

paiji2_carpooling/templates/carpooling/carpool/list.html
{% extends "home/layout_three_columns.html" %}


{% load i18n %}
{% load bootstrap3 %}
{% load profile %}


{% block title%}{% trans 'Carpools' %}{% endblock %}


{% block content %}
<div class="well">
    <a class="btn btn-primary btn-block text-center" href="{% url 'carpool-create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        {% trans "Add a carpool offer/search" %}
    </a>

    <h3>{% trans 'Last carpools list' %}</h3>

    <ul class="list-unstyled">
        {% for cov in covs %}
            <li class="cov-item{% if not cov.isGood %} text-muted{% endif %}">

                {% profile_link cov.author %}

                {% if cov.annonce_type == 0 %}
                    <span class="label {% if cov.isGood %}label-success{% else %}label-default{% endif %}">
                        {% trans 'Offer' context "1st p sg" %}
                    </span>
                    {% else %}
                    <span class="label {% if cov.isGood %}label-danger{% else %}label-default{% endif %}">
                        {% trans 'Search' context "1st p sg" %}
                    </span>
                {% endif %}

                <span class="label {% if cov.isGood %}label-primary{% else %}label-default{% endif %}">
                    {{ cov.good_until|date:'DATETIME_FORMAT' }}
                </span>

                <div class="pull-right">
                {% if cov.author == request.user %}
                    <a href="{% url 'carpool-edit' cov.id %}"><i class="fa fa-pencil"></i></a>
                    <a href="{% url 'carpool-delete' cov.id %}"><i class="fa fa-trash-o"></i></a>
                {% else %}
                    {% with subject='['|add:_('carpooling')|add:'] '|add:_('About')|add:' : "'|add:cov.notes|add:'"' %}
                    {% mail_link cov.author _('contact') subject %}
                    {% endwith %}
                {% endif %}
                </div>

                <br/>

                {{ cov.notes }}

                <span class="text-muted"><small>{% blocktrans with TimeSince=cov.posted_at|timesince %}{{ TimeSince }} ago{% endblocktrans %}</small></span>

                <hr/>
            </li>

        {% endfor %}
    </ul>

    <div class="pagination-container">
        {% bootstrap_pagination page_obj %}
    </div>
</div>
{% endblock %}

paiji2_carpooling/templates/cov/cov_block.html
{% load readmore %}
{% load i18n %}

<h3>{% trans 'Carpool' %}</h3>
<div class="row text-center">
    {% if request.user.is_authenticated %}
        <div class="col-sm-6">
            <a class="btn btn-sm btn-default" href="{% url 'cov-add' %}">
                {% trans 'Add a carpool' %}
            </a>
        </div>
    {% endif %}
    <div class="col-sm-6">
        <a class="btn btn-sm btn-default" href="{% url 'cov-list' %}">
            {# Translators: Archives #}
            {% trans 'Records' %}
        </a>
    </div>
</div>

<ul class="list-unstyled">
    {% for item in cov %}
        <li>
        {% if item.author == request.user %}
            <div class="pull-right">
                <a href="{% url 'cov-edit' item.id %}"><i class="fa fa-pencil"></i></a>
                <a href="{% url 'cov-delete' item.id %}"><i class="fa fa-trash-o"></i></a>
            </div>
        {% endif %}

        <span>
            <a href="mailto:{{ item.author.email }}?subject=[Paiji2][{% trans 'Carpool' %}] {% trans 'About' %}{{ ' : "'|add:item.notes|add:'"'|urlencode }}">
            <i class="glyphicon glyphicon-envelope"></i>
            {{ item.author.first_name }}
            </a>

            {% if item.annonce_type == 0 %}
                <span class="label label-success">
                {% trans 'Offer' context "1st p sg" %}
                </span>
            {% else %}
                <span class="label label-danger">
                {% trans 'Search' context "1st p sg" %}
                </span>
            {% endif %}
                <span class="label label-primary">
                {{ item.good_until|date:'SHORT_DATETIME_FORMAT' }}
                </span>
            {{ item.notes|readmore:10 }}
        </span>

            <span class="text-muted"><small>{% blocktrans with TimeSince=item.posted_at|timesince %}{{ TimeSince }} ago{% endblocktrans %}</small></span>
        </li>
    {% endfor %}
</ul>

paiji2_carpooling/templates/cov/cov_list.html
{% extends "home/layout_three_columns.html" %}
{# load staticfiles #}
{% load i18n bootstrap3 %}

{# block style #}<!-- <link rel="stylesheet" type="text/css" href="{# static 'cov/css/cov.css' #}" /> -->{# endblock #}

{% block title%}{% trans 'Carpools' %}{% endblock %}

{% block content %}

    <div class="well">

        <a class="btn btn-primary btn-block text-center" href="{% url 'cov-add' %}">
            <span class="glyphicon glyphicon-plus"></span>
            {% trans "Add a carpool offer/search" %}
        </a>

        <h3>{% trans 'Last carpools list' %}</h3>

        <ul class="list-unstyled">
            {% for cov in covs %}
            {% if not cov.isGood %}
                <li class="cov-item text-muted">
                    <span class="begin-time">
                    <span>
                        <i class="glyphicon glyphicon-envelope"></i>
                        {{ cov.author.first_name }} {{ cov.author.last_name }}
                    </span>
                    {% if cov.annonce_type == 0 %}
                        <span class="label label-default">
                        {% trans 'Offer' context "1st p sg" %}
                        </span>
                    {% else %}
                        <span class="label label-default">
                        {% trans 'Search' context "1st p sg" %}
                        </span>
                    {% endif %}
                        <span class="label label-default">
                        {{ cov.good_until|date:'DATETIME_FORMAT' }}
                        </span>
                    </span>
                    {{ cov.notes }}<br/>
                    <span class="text-muted"><small>{% blocktrans with TimeSince=cov.posted_at|timesince %}{{ TimeSince }} ago{% endblocktrans %}</small></span>
            {% else %}
            <li class="cov-item">
                <span class="begin-time">
                <a href="mailto:{{ item.author.email }}?subject=[Paiji2][{% trans 'Carpool' %}] {% trans 'About' %}{{ ' : "'|add:cov.notes|add:'"'|urlencode }}">
                <i class="glyphicon glyphicon-envelope"></i>
                {{ cov.author.first_name }} {{ cov.author.last_name }}
                </a>
                {% if cov.annonce_type == 0 %}
                    <span class="label label-success">
                    {% trans 'Offer' context "1st p sg" %}
                    </span>
                {% else %}
                    <span class="label label-danger">
                    {% trans 'Search' context "1st p sg" %}
                    </span>
                {% endif %}
                    <span class="label label-primary">
                    {{ cov.good_until|date:'DATETIME_FORMAT' }}
                    </span>
                    </span>
                {{ cov.notes }}<br/>
                <span class="text-muted"><small>{% blocktrans with TimeSince=cov.posted_at|timesince %}{{ TimeSince }} ago{% endblocktrans %}</small></span>
            {% endif %}

            {% if cov.author == request.user %}
                <div class="pull-right">
                    <a href="{% url 'cov-edit' cov.id %}"><i class="fa fa-pencil"></i></a>
                    <a href="{% url 'cov-delete' cov.id %}"><i class="fa fa-trash-o"></i></a>
                </div>
            {% endif %}
            
            </li>
            <hr>

            {% endfor %}
        </ul>


        {% comment %}
        <div class="pagination-container">
        <ul class="pagination pagination-sm">
            <li{% if not page_obj.has_previous %} class="disabled"{% endif %}>
                {% if page_obj.has_previous %}
                <a href="{% url 'cov-list' page=page_obj.previous_page_number %}">
                {% else %}
                <a href="#">
                {% endif %}
                    &laquo;
                </a>
            </li>
            <li class="disabled"><a href="#">...</a></li>
            <li class="active"><a href="#">{{ page_obj.number }}</a></li>
            <li class="disabled"><a href="#">...</a></li>
            <li{% if not page_obj.has_next %} class="disabled"{% endif %}>
                {% if page_obj.has_next %}
                <a href="{% url 'cov-list' page=page_obj.next_page_number %}">
                {% else %}
                <a href="#">
                {% endif %}
                    &raquo;
                </a>
            </li>
        </ul>
        </div>
        {% endcomment %}
        <div class="pagination-container">
        {% bootstrap_pagination page_obj %}
        </div>
    </div>
{% endblock %}

paiji2_carpooling/templates/cov/covoiturage_confirm_delete.html
{% extends "home/layout_three_columns.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans 'Carpool deletion confirmation' %}{% endblock %}

{% block content %}
<div class="well">
    <h3>{% trans 'Do you really want to delete this carpool ?' %}</h3>
    <p>'{{ object.notes }}'</p>

    <form action="" method="post" role="form">
        {% csrf_token %}

        <input type="hidden" value="{{ request.META.HTTP_REFERER }}" name="next" />

        {% buttons %}
            <button type="submit" class="btn btn-danger btn-block">
                {% trans 'Delete' %}
            </button>
        {% endbuttons %}
        <div class="clearfix"></div>
    </form>
</div>

{% endblock %}

paiji2_carpooling/templates/cov/covoiturage_form.html
{% extends "home/layout_three_columns.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}
    {% if form.instance and form.instance.pk %}
        {% trans 'Edit a carpool' %}
    {% else %}
        {% trans 'Offer/search a carpool' %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="well">
        {% if form.instance and form.instance.pk %}
            <h3>{% trans 'Edit a carpool' %}</h3>
        {% else %}
            <h3>{% trans 'Offer/search a carpool' %}</h3>
        {% endif %}

        <form action="{{ request.get_full_path }}" method="post" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label for="annonceur">{% trans 'Announcer' %}</label>
                <p>{{ request.user.first_name }} ({{ request.user.email }})</p>
            </div>

            <div class="form-group">
                <label for="annonce_type">{% trans 'Advert type' %}</label>
                {% bootstrap_field form.annonce_type show_label=False %}

                <label for="good_until">{% trans 'Departure time' %}</label>
                {% bootstrap_field form.good_until show_label=False %}

                <label for="annonceur">{% trans 'Notes' %}</label>
                <p class="help-block">{% trans 'Ex: Metz-Paris-Compiègne, on Friday around 5pm, 3 places 15 €, back on Sunday at 6pm' %}</p>
                {% bootstrap_field form.notes show_label=False %}
            </div>

            <input type="hidden" value="{{ request.META.HTTP_REFERER }}" name="next" />
            <br />
            {% buttons %}
                <button type="submit" class="btn btn-primary btn-block text-center">
                    {% if form.instance and form.instance.pk %}
                        {% trans 'Update' %}
                    {% else %}
                        {% trans 'Publish' %}
                    {% endif %}
                </button>
            {% endbuttons %}
            <div class="clearfix"></div>
        </form>
    </div>
{% endblock %}

paiji2_carpooling/templates/home/layout_three_columns.html
{% load cov_tag %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <div id="block">
            {% get_cov %}
        </div>
        <div id="main" class="container clearfix">
            <div class="row">
                <div class="col-md-6">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </body>

</html>